package clivet268.SecureLine.Commands;

import clivet268.Enforcry;

import java.util.ArrayList;

public abstract class ExacutableCommand implements Runnable{
    String name = this.getClass().getSimpleName();
    public ArrayList<? super Object> output = new ArrayList<>();
    public ArrayList<String> input = new ArrayList<>();
    /**
     * 0 - none
     * 1 - text
     */
    private int tnt = 0;

    /**
     * @return returns the output mode of this command (texting or not)
     */
    public int getTnt(){
        return tnt;
    }

    /**
     * @return returns the command prompts to be sent out to the sender,by default an empty arraylist
     */
    public ArrayList<String> commandPrompts(){
            ArrayList<String> ps = new ArrayList<>();
        return  ps;
    }
    boolean closeflag =true;

    //TODO no longer SL, EFCTP
    /**
     * Populates the SLcommands array to be gotten by sender
     */
    public void init(){
        Enforcry.SLcommands.put(name.toLowerCase(), this);
    }

    /**
     * Runs the function stored inside and populates the output array if there are outputs
     */
    @Override
    public void run() {
        this.output.add("0");
    }

    //TODO needed with EFCTP?
    public int outbytecode(){
        return -1;
    }

    /**
     * @return returns the outputs generated by {@link #run()}
     */
    public ArrayList<? super Object> getOutput(){
        return output;
    }
}
